version: '3'

services:
  app:
    container_name: FastAPI
    build: .
    volumes:
      - ./src:/src
    ports:
      - "9004:9004"
    env_file:
      - .dev_env
    command: uvicorn main:app --reload --host 0.0.0.0 --port 9004
#TODO: Mysqlコンテナを作成する