version: '3'

services:
  app:
    container_name: FastAPI
    build: .
    volumes:
      - ./src:/src
    ports:
      - "9004:9004"
    env_file:
      - .test_env
    command: uvicorn main:app --reload --host 0.0.0.0 --port 9004
    networks:
      - mytest
  
  mariadb:
    image: mariadb:10.6
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: Makt0112pc-49466
      MYSQL_DATABASE: app-data
      MYSQL_USER: poteto1212
      MYSQL_PASSWORD: Makt0112pc-49466
    ports:
      - "3306:3306"
    networks:
      - mytest

networks:
  mytest:



  