version: '3'

services:
  app:
    container_name: FastAPI
    build: .
    volumes:
      - ./src:/src
    ports:
      - "9004:9004"
    environment:
      - MYSQL_URL=mysql+mysqlconnector://poteto1212:Makt0112pc-49466@127.0.0.1:3306/app-data
    command: uvicorn main:app --reload --host 0.0.0.0 --port 9004
  

  