"""ユーザーテーブル作成

Revision ID: 8eaf2c2a07e2
Revises: 
Create Date: 2024-01-25 09:19:36.782326

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '8eaf2c2a07e2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nickname', sa.String(length=15), nullable=True),
    sa.Column('user_name', sa.String(length=30), nullable=True),
    sa.Column('password', sa.String(length=15), nullable=True),
    sa.Column('security_ask', sa.Integer(), nullable=True),
    sa.Column('security_ask_answer', sa.String(length=20), nullable=True),
    sa.Column('graduate', sa.Integer(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_user_name'), 'users', ['user_name'], unique=True)
    op.drop_table('NewTable')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('NewTable',
    sa.Column('Column1', mysql.VARCHAR(length=100), nullable=True),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_index(op.f('ix_users_user_name'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
