"""パスワードの文字数を修正

Revision ID: dd7c4b887052
Revises: 75eb163b1729
Create Date: 2024-01-26 09:19:32.648481

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'dd7c4b887052'
down_revision: Union[str, None] = '75eb163b1729'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password',
               existing_type=mysql.VARCHAR(length=15),
               type_=sa.String(length=70),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password',
               existing_type=sa.String(length=70),
               type_=mysql.VARCHAR(length=15),
               existing_nullable=True)
    # ### end Alembic commands ###
