name: build
on: [push]
jobs:
  build_job:
    name: build
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: build-command
        run: |
          docker-compose -f docker-compose_test.yml up -d 
      - name: Wait for MySQL to be ready
        run: sleep 30s
      - name: migrate
        run: |
          docker-compose -f docker-compose_test.yml run app bash -c "cd db ; alembic upgrade head"
      - name: insert_seed
        run: |
          docker-compose -f docker-compose_test.yml run app bash -c "python ./seeds/users_seed.py"
      - name: test
        run: |
          docker-compose -f docker-compose_test.yml run app pytest /src/tests/test_main.py
      - name: docker-down
        run: |
          docker-compose -f docker-compose_test.yml down
